name: tcc_iago
description: A new Flutter project.
publish_to: 'none'

version: 0.1.0+100

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  flutter_triple: ^2.0.0
  camera: ^0.10.5+4
  dio: ^5.3.3
  uuid: ^4.1.0
  syncfusion_flutter_charts: ^20.2.43
  image: ^4.1.3
  extended_image: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  triple_test: ^2.0.0
  modular_test: ^2.0.0

flutter:
  uses-material-design: true